export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "C#"
  | ".NET"
  | "Postman"
  | "Linux"
  | "Nginx"
  | "Composer"
  | "OOP"
  | "MVC Architecture"
  | "RESTful APIs"
  | "System Optimization"
  | "Database Design"
  | "Rust"
  | "Angular"
  | "Sequelize"
  | "JWT / RBAC"
  | "SQLite"
  | "Qdrant"
  | "OpenCLIP"
  | "pgvector"
  | "Ollama"
  | "LLM APIs"
  | "LoRA / PEFT"
  | "Hugging Face"
  | "OpenAPI"
  | "OWASP API Top 10"
  | "Noise Protocol"
  | "Tesseract OCR"
  | "GitHub Actions";

export type ValidCategory =
  | "C#"
  | ".NET"
  | "Postman"
  | "Linux"
  | "Nginx"
  | "Composer"
  | "OOP"
  | "MVC Architecture"
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "AI & Search"
  | "Developer Tools"
  | "Security"
  | "Business Systems";

export type ValidExpType = "Personal Project" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "experience"
  | "career"
  | "contact"
  | "contributions"
  | "resume"
  | "blog";
