export const siteConfig = {
  name: "HOUY SENGLEANG | Full Stack Developer",
  authorName: "HOUY SENGLEANG",
  username: "hoysengleang",
  description:
    "Results-oriented Developer with expertise in API architecture and Scalable Web Solutions. I am an ambitious team player known for my resilience and creative approach to problem-solving. committed to building efficient software that drives business growth.",
  url: "https://hoysengleang.vercel.app",
  links: {
    twitter: "https://t.me/hoysengleang", // Using telegram as twitter link for now since resume lists telegram
    github: "https://github.com/hoysengleang",
  },
  ogImage: "https://hoysengleang.vercel.app/og.png", // Placeholder
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Hoysengleang",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
