export const siteConfig = {
  name: "HOUY SENGLEANG | Backend Developer",
  authorName: "HOUY SENGLEANG",
  username: "hoysengleang",
  description:
    "Detail-oriented Backend Developer with over 3 years of experience in Fintech systems and API architecture. Currently serving as an R&D Officer specializing in technical research, environment standardization using Docker, and performance benchmarking. Proven track record in architecting secure, 100% accurate financial systems—including Core Banking and Pawn Management—with a focus on high-volume transaction reliability and scalable system design.",
  url: "https://hoysengleang.vercel.app",
  links: {
    twitter: "https://t.me/hoysengleang", // Using telegram as twitter link for now since resume lists telegram
    github: "https://github.com/hoysengleang",
  },
  ogImage: "https://hoysengleang.vercel.app/og-image",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords: [
    "Hoysengleang",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
